# Generated by Django 4.2.7 on 2023-12-08 07:39

import ais.valid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_part_number', models.CharField(max_length=200)),
                ('ais', models.FileField(upload_to='static/ais', validators=[ais.valid.validate])),
                ('ApprovedByProduction', models.BooleanField(default=False, verbose_name='Approved by production')),
                ('ApprovedByQUA', models.BooleanField(default=False, verbose_name='Approved by Quality')),
                ('ApprovedByHod', models.BooleanField(default=False, verbose_name='Approved by Hod')),
                ('reject', models.BooleanField(default=False, verbose_name='Approved by Hod')),
            ],
        ),
        migrations.CreateModel(
            name='hod_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='oparator_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='production_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='quality_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='REJECT_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('product_part_number_01', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.ais')),
            ],
        ),
        migrations.CreateModel(
            name='QUALITY_Approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.ais')),
            ],
        ),
        migrations.CreateModel(
            name='PED_Approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.ais')),
            ],
        ),
        migrations.CreateModel(
            name='Hod_Approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ais.ais')),
            ],
        ),
    ]
