# Generated by Django 4.2.7 on 2023-12-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reject_1',
            name='command',
        ),
    ]
