# Generated by Django 4.2.7 on 2023-12-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0003_rename_reject_1_hod_reject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ais',
            name='revision_num',
            field=models.IntegerField(default='1', verbose_name='revision num'),
        ),
    ]
