# Generated by Django 4.2.7 on 2023-12-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0004_alter_ais_revision_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod_reject',
            name='command',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ped_reject',
            name='command',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='production_reject',
            name='command',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quality_reject',
            name='command',
            field=models.TextField(default=''),
        ),
    ]
