# Generated by Django 4.2.7 on 2023-12-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0006_remove_hod_reject_command_remove_ped_reject_command_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ais',
            name='command',
        ),
        migrations.AddField(
            model_name='hod_reject',
            name='command',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ped_reject',
            name='command',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='production_reject',
            name='command',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quality_reject',
            name='command',
            field=models.TextField(default=''),
        ),
    ]
