# Generated by Django 4.2.7 on 2023-12-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0007_remove_ais_command_hod_reject_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ais',
            name='ApprovedByProductionUser',
            field=models.CharField(default='', max_length=100),
        ),
    ]
