# Generated by Django 4.2.7 on 2023-12-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0008_ais_approvedbyproductionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ais',
            name='ApprovedByQUAUser',
            field=models.CharField(default='', max_length=100),
        ),
    ]
