# Generated by Django 4.2.7 on 2023-12-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0009_ais_approvedbyquauser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ais',
            name='ApprovedByQUAUser',
        ),
        migrations.AlterField(
            model_name='ais',
            name='ApprovedByProductionUser',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
