# Generated by Django 4.2.7 on 2023-12-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0010_remove_ais_approvedbyquauser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ais',
            name='ApprovedByProductionUser',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
