# Generated by Django 4.2.7 on 2023-12-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0011_alter_ais_approvedbyproductionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ais',
            name='ApprovedByHodUser',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='ais',
            name='ApprovedByQUAUser',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='ais',
            name='ApprovedBypedUser',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
