# Generated by Django 4.2.7 on 2023-12-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0012_ais_approvedbyhoduser_ais_approvedbyquauser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ais',
            name='ApprovedByHodUser',
            field=models.CharField(default='Admin_2', max_length=100),
        ),
        migrations.AlterField(
            model_name='ais',
            name='ApprovedByQUAUser',
            field=models.CharField(default='Admin_1', max_length=100),
        ),
    ]
