# Generated by Django 4.2.7 on 2023-12-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0013_alter_ais_approvedbyhoduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ais',
            name='ApprovedByHodUser',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ais',
            name='ApprovedByProductionUser',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ais',
            name='ApprovedByQUAUser',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ais',
            name='ApprovedBypedUser',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
