# Generated by Django 4.2.7 on 2023-12-17 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0015_alter_ais_approvedbyhoduser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ais',
            name='ApprovedByHoddate',
            field=models.DateTimeField(default=datetime.date(2023, 12, 18), verbose_name='date time '),
        ),
        migrations.AddField(
            model_name='ais',
            name='ApprovedByProductiondate',
            field=models.DateTimeField(default=datetime.date(2023, 12, 18), verbose_name='date time '),
        ),
        migrations.AddField(
            model_name='ais',
            name='ApprovedByQUAdate',
            field=models.DateTimeField(default=datetime.date(2023, 12, 18), verbose_name='date time '),
        ),
        migrations.AddField(
            model_name='ais',
            name='ApprovedBypeddate',
            field=models.DateTimeField(default=datetime.date(2023, 12, 18), verbose_name='date time '),
        ),
        migrations.AddField(
            model_name='ais',
            name='RejectByPedcommand',
            field=models.CharField(default='REJRCT BY PED', max_length=100),
        ),
        migrations.AddField(
            model_name='ais',
            name='RejectdByHodcommand',
            field=models.CharField(default='REJRCT BY HOD', max_length=100),
        ),
        migrations.AddField(
            model_name='ais',
            name='RejectdByProductioncommand',
            field=models.CharField(default='REJRCT PRODUCTION', max_length=100),
        ),
        migrations.AddField(
            model_name='ais',
            name='RejectdByQUAcommand',
            field=models.CharField(default='REJRCT QUALITY', max_length=100),
        ),
        migrations.AlterField(
            model_name='ais',
            name='RejectByPed',
            field=models.BooleanField(default=False, verbose_name='Reject by Ped'),
        ),
        migrations.AlterField(
            model_name='ais',
            name='RejectdByHod',
            field=models.BooleanField(default=False, verbose_name='Reject by Hod'),
        ),
        migrations.AlterField(
            model_name='ais',
            name='RejectdByProduction',
            field=models.BooleanField(default=False, verbose_name='Reject byProduction'),
        ),
        migrations.AlterField(
            model_name='ais',
            name='RejectdByQUA',
            field=models.BooleanField(default=False, verbose_name='Reject by Quality'),
        ),
    ]
