# Generated by Django 4.2.7 on 2023-12-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0017_alter_ais_approvedbyhoddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ais',
            name='ApprovedByHoddate',
            field=models.CharField(default='hod date', max_length=100),
        ),
        migrations.AlterField(
            model_name='ais',
            name='ApprovedByProductiondate',
            field=models.CharField(default='production date', max_length=100),
        ),
        migrations.AlterField(
            model_name='ais',
            name='ApprovedByQUAdate',
            field=models.CharField(default='quality date', max_length=100),
        ),
        migrations.AlterField(
            model_name='ais',
            name='ApprovedBypeddate',
            field=models.CharField(default='ped date', max_length=100),
        ),
    ]
