# Generated by Django 4.2.7 on 2023-12-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0018_alter_ais_approvedbyhoddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ais',
            name='product_part_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
