# Generated by Django 4.2.7 on 2024-01-03 07:30

import ais.valid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0019_alter_ais_product_part_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_part_number', models.CharField(max_length=200, unique=True)),
                ('pdi', models.FileField(upload_to='static/pdi', validators=[ais.valid.validate])),
            ],
        ),
    ]
